config/routes.rb
Rails.application.routes.draw do


  resources :companies
  mount Ckeditor::Engine => '/ckeditor'
  get 'comments/create'

  get 'd/:short/metas/:id/nova', to: 'goals#new',as: :new_direction_goal
  get 'células/:id/metas/:id/nova', to: 'goals#new_goal',as: :new_cellule_goal
  get 'empresa/:id/metas/:id/nova', to: 'goals#new_goal_company',as: :new_company_goal

 
  get 'metas/:id/tarefas/:id/nova', to: 'tasks#new', as: :new_goal_task
  post 'tarefas/:id/confimation',to: 'goals#confimation',as: :confimation_goal_task
  post 'tarefas/:id/not_confirmation', to:'goals#not_confimation',as: :not_confimation_task
  
  resources :tasks, except: [:new,:index]
  resources :goals, except: [:new,:index]
  resources :skills

  root to: "welcome#home"
  
  resources :forums do
    member do
      put "like", to: "forums#vote"
      put "dislike", to: "forums#downvote"
    end
    resources :notes
  end

  resources :projects do
    resources :tecnologies
  end
  resources :cellules
  resources :directions,:path=>'d'



  resources :articles do
    member do
      put "like", to: "articles#vote"
      put "dislike", to: "articles#downvote"
    end
    resources :comments
  end

  get 'users/:id/change', to: 'users#change', as: :change_user
  post 'users/:id/give_up', to: 'users#give_up', as: :give_up_user
  post 'users/:id/accept', to: 'users#accept', as: :accept_user
  devise_for :users
  resources :users
  get 'welcome/home'
  get 'tags/:tag', to: 'forums#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :projects, :path =>'projetos'
  resources :cellules, :path=>'celulas'
  resources :directions

end

app/models/cellule.rb
class Cellule < ApplicationRecord
  validates :name,presence: true
  
  belongs_to :direction, optional: true
  belongs_to :manager, :class_name => 'User', optional: true,:foreign_key => 'manager_id'
  has_many :cellule_users
  has_many :users
  has_many :goals
  
  has_many :history_cellules
end

app/controllers/cellules_controller.rb
class CellulesController < ApplicationController
  before_action :set_cellule, only: [:show, :edit, :update, :destroy]
  before_action :redirect_not_allowed, except: [:show,:index]


  # GET /cellules
  # GET /cellules.json
  def index
    @cellules = Cellule.all
  end

  # GET /cellules/1
  # GET /cellules/1.json
  def show
  end

  # GET /cellules/new
  def new
    @cellule = Cellule.new
  end

  # GET /cellules/1/edit
  def edit
  end

  # POST /cellules
  # POST /cellules.json
  def create
    @cellule = Cellule.new(cellule_params)

    respond_to do |format|
      if @cellule.save
        format.html { redirect_to @cellule, notice: 'Cellule was successfully created.' }
        format.json { render :show, status: :created, location: @cellule }
      else
        format.html { render :new }
        format.json { render json: @cellule.errors, status: :unprocessable_entity }
      end
    end
    
    
  end

  # PATCH/PUT /cellules/1
  # PATCH/PUT /cellules/1.json
  def update
    respond_to do |format|
      if @cellule.update(cellule_params)
        format.html { redirect_to @cellule, notice: 'Cellule was successfully updated.' }
        format.json { render :show, status: :ok, location: @cellule }
      else
        format.html { render :edit }
        format.json { render json: @cellule.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # DELETE /cellules/1
  # DELETE /cellules/1.json
  def destroy
    @cellule.destroy
    respond_to do |format|
      format.html { redirect_to cellules_url, notice: 'Cellule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cellule
      @cellule = Cellule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cellule_params
      params.require(:cellule).permit(:name, :direction_id, :manager_id)
    end

    def redirect_not_allowed
      if cannot? :manager, @cellule
        redirect_to root_path
      end
    end

end

app/views/cellules/_form.html.erb
<%= form_with(model: cellule, local: true) do |form| %>
  <% if cellule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cellule.errors.count, "error") %> prohibited this cellule from being saved:</h2>

      <ul>
      <% cellule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="container">
    <%if current_page?(action:'new')%>
      <h1>Nova célula</h1>
    <%else%>
      <h1>Editar célula</h1>
    <%end%>
    <div class="field">
      <h3><%= form.label :manager_id %></h3>
      <%= form.collection_select :manager_id,User.all,:id , :name, :include_blank => true%>
    </div>
    
    <div class="field">
      <h3><%= form.label :direction_id%></h3>
      <%= form.collection_select :direction_id, Direction.all,:id, :name, :include_blank => true %>
    </div>

    <div class="field">
      <h3><%= form.label :name, "Nome" %></h3>
      <%= form.text_field :name %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/cellules/edit.html.erb
<section id="forms">
    <%= render "form", cellule: @cellule %>
    <%= link_to cellules_path do %>
        <button type="button" class="btn btn-primary back">
            <i class="fas fa-arrow-left"></i>
        </button>
    <% end %>
</section>

app/views/cellules/index.html.erb
<section id="content" class="celulas">
  <%= render 'shared/sidebar' %>


  <div id="page-content" class="container">

    <div class="page-header">
      <h1> <i class="fas fa-boxes"></i> Células</h1>
      <%if can? :create, Cellule%>
      <%= link_to new_cellule_path, class: "nav-link" do %>
      <button type="button" class="btn btn-primary header-button">
        <i class="fas fa-plus"></i> Célula
      </button>
      <% end %>
      <%end%>
    </div>

    <div class="page-body">
      <table>
        <thead>
          <th>Celula</th>
          <th>Gerente</th>
        </thead>
        <% for cellule in @cellules%>
        <tr>
          <td>
            <%=link_to cellule.name, cellule_path(cellule)%>
          </td>
          <td>
            <% if cellule.manager %>
              <%=link_to cellule.manager.name, user_path(cellule.manager.id)%>
            <% else %>
              Posição vaga
            <% end %>
          </td>
        </tr>
        <%end%>
      </table>

    </div>
  </div>
</section>

app/views/cellules/new.html.erb
<section id="forms">
    <%= render 'form', cellule: @cellule %>
    <%= link_to cellules_path do %>
        <button type="button" class="btn btn-primary back">
            <i class="fas fa-arrow-left"></i>
        </button>
    <% end %>
</section>

app/views/cellules/show.html.erb
<section id="content">
  <%= render 'shared/sidebar' %>


  <div id="page-content" class="container">

    <div class="page-header">
      <h1><i class="fas fa-boxes"></i> Célula de <%= @cellule.name %></h1>
      <div class="header-buttons">
        <% if can? :manage, @cellule%>
          <%= link_to new_cellule_goal_path(@cellule.id) do %>
            <button type="button" class="btn btn-primary header-button small">
              <i class="fas fa-plus"></i> Meta
            </button>
          <% end %>
          <%= link_to edit_cellule_path(@cellule) do %>
            <button type="button" class="btn btn-primary header-button small">
              <i class="fas fa-edit"></i>
            </button>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="page-body">
      <% if @cellule.manager %>
        <div class="head">
          <h2>Gerente</h2>
          <div class="members">
            <div class="member">
              <%= link_to @cellule.manager do %>
                <% if @cellule.manager.avatar_url %>
                  <%= image_tag  @cellule.manager.avatar_url %>
                <% else %>
                  <%= image_tag  "wolf-avatar.jpg" %>
                <% end %>
              <% end %>
              <%= link_to @cellule.manager do %>
                <%= @cellule.manager.name %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>

      <% if @cellule.manager && @cellule.users.where.not(id: @cellule.manager_id).any? %>
        <div class="separator">
        </div>
      <% end %>

      <% if @cellule.users.where.not(id: @cellule.manager_id).any? %>
        <div class="team">
          <h2>Membros</h2>
          <div class="members">
            <% for user in @cellule.users.where.not(id: @cellule.manager_id)%>
              <div class="member">
                <%= link_to user do%>
                  <% if user.avatar_url %>
                    <%= image_tag  user.avatar_url %>
                  <% else %>
                    <%= image_tag  "wolf-avatar.jpg" %>
                  <% end %>
                <% end %>
                <%= link_to user do%>
                  <%=user.name%>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>

      <% if @cellule.name == "Criação" %>
        <% if @cellule.users.where.not(id: @cellule.manager_id).any? %>
          <div class="team">
            <h2>Membros</h2>
            <div class="members">
              <% for user in User.where.not(creation: nil) %>
                <% if user.id != @cellule.manager_id %>
                  <div class="member">
                    <%= link_to user do%>
                      <% if user.avatar_url %>
                        <%= image_tag  user.avatar_url %>
                      <% else %>
                        <%= image_tag  "wolf-avatar.jpg" %>
                      <% end %>
                    <% end %>
                    <%= link_to user do%>
                      <%=user.name%>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>

      <% if @cellule.users.none? %>
        <h3>Ops! Não tem ninguém aqui :(</h3>
      <% end %>

      <% if @cellule.goals.any? %>
        <div class="goals">
          <div class="goal-button">
            <h2>Metas<h2>
            <div class="goals-list">
              <% for goal in @cellule.goals %>
                <div class="goal-single">
                  <%= link_to edit_goal_path(goal) do %>
                    <button type="button" class="btn btn-primary edit-goal">
                      <i class="fas fa-edit"></i>
                    </button>
                  <% end %>
                  <%= link_to goal_path(goal) do %>
                    <button type="button" class="btn btn-primary edit-goal">
                      <i class="fas fa-external-link-alt"></i>
                    </button>
                  <% end %>
                  <p><%= goal.name %></p>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</section>