config/routes.rb
Rails.application.routes.draw do


  resources :companies
  mount Ckeditor::Engine => '/ckeditor'
  get 'comments/create'

  get 'd/:short/metas/:id/nova', to: 'goals#new',as: :new_direction_goal
  get 'células/:id/metas/:id/nova', to: 'goals#new_goal',as: :new_cellule_goal
  get 'empresa/:id/metas/:id/nova', to: 'goals#new_goal_company',as: :new_company_goal

 
  get 'metas/:id/tarefas/:id/nova', to: 'tasks#new', as: :new_goal_task
  post 'tarefas/:id/confimation',to: 'goals#confimation',as: :confimation_goal_task
  post 'tarefas/:id/not_confirmation', to:'goals#not_confimation',as: :not_confimation_task
  
  resources :tasks, except: [:new,:index]
  resources :goals, except: [:new,:index]
  resources :skills

  root to: "welcome#home"
  
  resources :forums do
    member do
      put "like", to: "forums#vote"
      put "dislike", to: "forums#downvote"
    end
    resources :notes
  end

  resources :projects do
    resources :tecnologies
  end
  resources :cellules
  resources :directions,:path=>'d'



  resources :articles do
    member do
      put "like", to: "articles#vote"
      put "dislike", to: "articles#downvote"
    end
    resources :comments
  end

  get 'users/:id/change', to: 'users#change', as: :change_user
  post 'users/:id/give_up', to: 'users#give_up', as: :give_up_user
  post 'users/:id/accept', to: 'users#accept', as: :accept_user
  devise_for :users
  resources :users
  get 'welcome/home'
  get 'tags/:tag', to: 'forums#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :projects, :path =>'projetos'
  resources :cellules, :path=>'celulas'
  resources :directions

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates_format_of :email, with: /\A([^@\s]+)@injunior.com\z/i, on: [:create,:update]

  has_many :forums
  has_many :notes
  has_many :articles
  has_many :comments

  acts_as_voter
  
  belongs_to :direction,optional: true
  belongs_to :direction_fusion, :class_name => 'Direction', optional: true,:foreign_key => 'direction_fusion_id'
  
  belongs_to :cellule, optional: true
  belongs_to :creation,:class_name => "Cellule", :foreign_key => 'creation_id',optional: true
  has_many :history_cellules
  
  
  mount_uploader :avatar, AvatarUploader 

  has_many :user_projects
  has_many :projects, through: :user_projects

  has_many :user_skills
  has_many :skills,through: :user_skills
  accepts_nested_attributes_for :skills, allow_destroy: true

  has_many :direction_users


  enum kind:{
    standard: 1,
    manager: 2,
    director: 3, 
    admin: 4,
    gp_director: 5,
    pro_director: 6,
    pmo_manager: 7
  }

  def self.search(search)
    if search!='' and !search.nil?
      where(["name LIKE ?","%#{search}%"])
    else
      all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :change, :give_up, :accept]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    if @user.direction_id
      DirectionUser.create(user_id: @user.id, direction_id: @user.direction_id)
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    if @user.direction_id
      DirectionUser.create(user_id: @user.id, direction_id: @user.direction_id)
    end
    if @user.cellule_id || @user.creation_id
      
      @history=HistoryCellule.new
      @history.user_id=@user.id
    end
    if @user.cellule_id
      
      @history.cellule_id= @user.cellule_id
    end
    if @user.creation_id
 
      @history.creation_id=@user.creation_id
    end
    if @user.cellule_id || @user.creation_id
     
      @history.save
    end
  end



  def change
    
    
  end

  def give_up
    @user.update_attributes(direction_fusion_id: nil) 
    redirect_to @user
  end

  def accept
    @user.update_attributes(direction_id: @user.direction_fusion_id)
    @user.update_attributes(direction_fusion_id: nil)
    redirect_to @user
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :kind, :email, :direction_id, :direction_fusion_id,:avatar,{:skill_ids => []},:cellule_id, :creation_id, :password, skills_attributes: [:name, :_destroy, :id, :kind])
    end


    end

app/helpers/users_helper.rb
module UsersHelper
  def user_kind_option
      [['Padrão',:standard],['Adimistrador',:admin]]
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <%if current_page?(action:'new')%>
      <h1>Novo membro</h1>
    <%else%>
      <h1>Editar membro</h1>
    <%end%>

    <div class="field">
      <h3><%= f.label :name, "Nome" %></h3>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <h3><%= f.label :email, "E-mail" %></h3>
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <h3><%= f.label :password, "Senha" %></h3>
      <% if @minimum_password_length %>
        <p class="password-alert">(<%= @minimum_password_length %> characters minimum)</p>
      <% end %>
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
      <h3><%= f.label :password_confirmation, "Confirmar senha" %></h3>
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <%if current_user.admin?%>
      <div class="field">
        <h3><%= f.label :kind, "Posição" %></h3>
        <%= f.select :kind, user_kind_option %>
      </div>
    <% end %>
      
    <div class="field">
      <h3><%= f.label :direction, "Diretoria" %></h3>
      <%= f.collection_select :direction_id, Direction.all, :id , :name, :include_blank => true%>
    </div>

    <div class="field">
      <h3><%= f.label :cellule_id, "Célula de Projetos" %></h3>
      <%= f.collection_select :cellule_id, Cellule.where.not(name: 'Criação'), :id , :name, :include_blank => true%>
    </div>

    <div class="field">
      <h3><%= f.label :creation_id, "Célula compartilhada" %></h3>
      <%= f.collection_select :creation_id, Cellule.where(name: "Criação"), :id , :name, :include_blank => true%>
    </div>

    <div class="field">
      <%= f.fields_for :skills do |builder| %>
        <%= render 'skill_fields', f: builder %>
      <% end %>
      <%= link_to_add_fields "Add Skill", f, :skills %>
    </div>
    
    <div class="field">
      <h3 class="file-upload"><%= f.label :avatar, "Avatar" %></h3>
      <%= image_tag(@user.avatar_url) if @user.avatar? %>
      <%= f.file_field :avatar %>  
      <%= f.hidden_field :avatar_cache %>
    </div>

    <div class="actions">
      <%= f.submit "Salvar" %>
    </div>
  <% end %>
</div>

app/views/users/_skill_fields.html.erb
<fieldset>
  <%= f.label :name, "Habilidade:" %>
  <%= f.text_field :name %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/users/change.html.erb
<section class="fusao" id="content">
  <%= render 'shared/sidebar' %>
  <div id="fusao page-content" class="container">

    <div class="fusao-header page-header">
      <h1> <i class="fas fa-exchange-alt"></i> Fusão de diretorias</h1>
    </div>

    <div class="new page-body">
      <%= form_with(model: @user, local: true) do |form| %>

      <div class="field">
        <%= form.label :direction_fusion, "Mudar para diretoria de"%>
        <%= form.collection_select :direction_fusion_id, Direction.where.not(id: @user.direction.id), :id , :name, :include_blank => true%>
      </div>

      <div class="actions submit">
        <%= button_tag(type: "submit", class: "btn btn-primary botao") do %>
        <i class="fas fa-plus"></i> Fusão
        <% end %>
      </div>

      <%end%>
    </div>

  </div>

</section>

app/views/users/edit.html.erb
<section id="forms">
    <%= render 'form', user: @user %>
    <%= link_to users_path do %>
        <button type="button" class="btn btn-primary back">
            <i class="fas fa-arrow-left"></i>
        </button>
    <% end %>
</section>

app/views/users/index.html.erb
<section class="usuarios">
  <%= render 'shared/sidebar' %>
  <div id="usuarios">

      <div class="usuarios-header">
        <h1> <i class="fas fa-user"></i> Usuários</h1>
        <%if can? :create, User%>
        <%= link_to new_user_path, class: "nav-link" do %>
        <button type="button" class="btn btn-primary button-membro">
          <i class="fas fa-plus"></i>
          Usuário
        </button>
        <% end %>
        <%end%>
      </div>


    <div class="todos-usuarios">
      <% @users.each do |user| %>
      <%= link_to user_path(user.id) do %>
      <div class="usuario">
        <% if user.avatar_url %>
        <%= image_tag user.avatar_url %>
        <% else %>
        <%= image_tag "wolf-avatar.jpg"%>
        <% end %>
        <%= user.name %>
      </div>
      <%end%>
      <%end%>
    </div>


  </div>
</section>

app/views/users/new.html.erb
<section id="forms">
    <%= render 'form', user: @user %>
    <%= link_to users_path do %>
        <button type="button" class="btn btn-primary back">
            <i class="fas fa-arrow-left"></i>
        </button>
    <% end %>
</section>

app/views/users/show.html.erb
<section id="content">
  <%= render 'shared/sidebar' %>
  <div id="page-content" class="container">
    <div class="profile-header">
      <% if @user.avatar_url %>
        <%= image_tag  @direction.director.avatar_url %>
      <% else %>
        <%= image_tag  "wolf-avatar.jpg" %>
      <% end %>

      <h1><%= @user.name %></h1>

      <% if can? :update, @user%>
        <%= link_to edit_user_path(@user) do %>
          <button type="button" class="btn btn-primary edit">
            <i class="far fa-edit"></i>
          </button>
        <% end %>

        <% if @user.direction%>
          <% if !@user.direction_fusion%>
            <%= link_to change_user_path(@user) do %>
              <button type="button" class="btn btn-primary fusion">
                <i class="fas fa-exchange-alt"></i>
              </button>
            <% end %>
          <% else %>
            <div class="fusion-buttons">
              <%= link_to give_up_user_path, method: :post do %>
                <button type="button" class="btn btn-primary fusion">
                  <i class="fas fa-times"></i>
                </button>
              <% end %>
              <%= link_to accept_user_path, method: :post do %>
                <button type="button" class="btn btn-primary fusion">
                  <i class="fas fa-check"></i>
                </button>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="profile-body">
      <table class="info">
        <tr>
          <% if @user.direction%>
            <% if @user.direction_fusion %>
              <td><p>Antiga diretoria:</p> <% @user.direction.name %></td>
            <% else %>
              <td><p>Diretoria:</p> <%= @user.direction.name %></td>
              <% end %>
          <% end %>
  
          <% if @user.kind == 'director' %>
            <td><p>Encargo:</p> Direção</td> 
          <% else %>
            <td><p>Encargo:</p> Assessoria</td>
          <% end %>

          <% if @user.direction_fusion %>
            <td><p>Nova Diretoria:</p> <%= @user.direction_fusion.name %></td>
          <% end %>
        </tr>
      </table>

      <% if @user.skills.any? %>
        <div class="skills">
          <p>Habilidades:</p> <%= @user.skills.map{ |skill| skill.name }.join(', ') %></p>
        </div>
      <% end %>

      <% if @user.cellule || @user.creation %>
        <div class="cells">
          <p>Células:</p>
          <% if @user.cellule && @user.creation%>
            <%= @user.cellule.name %> e <%= @user.creation.name%>
          <% elsif @user.cellule %>
            <%=@user.cellule.name%>
          <% else%>
            <%= @user.creation.name%>
          <% end%>
        </div>
      <% end %>

      <% if @user.projects.any? %>
        <div class="projects">
          <h2><i class="fas fa-code"></i> Projetos</h2>
          <% if @user.projects.where.not(condition: 'finished').any? %>
            <div class="ongoing">
              <h3>Em andamento</h4>
              <table>
                <% for project in @user.projects.where.not(condition: 'finished')%>
                  <tr><td><%= link_to project.name, project %></td></tr>
                <% end %>
              </table>
            </div>
          <% end %>
          <% if @user.projects.where(condition: 'finished').length > 0 %>
            <div class="finished">
              <h3>Concluídos</h3>
              <table>
                <% for project in @user.projects.where(condition: 'finished')%>
                  <tr><td><%= project.name%></td></tr>
                <% end%>
              </table>
            </div>
          <% end %>
        </div>
      <% end %>

      <% if @user.history_cellules.any? || @user.direction_users.any? %>
        <div class="history">
          <h2><i class="fas fa-history"></i> Histórico</h2>
          <% if @user.direction_users.any? %>
            <div class="history-d">
              <h3>Diretorias</h3>
              <table>
                <% @aux=nil %>
                <thead>
                  <th>Diretoria</th>
                  <th>Data</th>
                </thead>
                <tbody>
                  <% for direction_user in @user.direction_users%>
                    <%if @aux==Direction.find_by(id: direction_user.direction_id)%>
                      <%next%>
                    <% end %>
                    <%@aux=Direction.find_by(id: direction_user.direction_id)%>
                    <tr>
                      <td><%= @aux.name%></td>
                      <td><%=l @aux.updated_at.to_date%></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% end %>

          <% if @user.history_cellules.any? %>
            <div class="history-c">
              <h3>Células</h3>
              <table>
                <% @aux=nil %>
                <thead>
                  <th>Célula</th>
                  <th>Data</th>
                </thead>
                <tbody>
                  <% for history in @user.history_cellules%>
                    <% if !@aux%>
                      <%@aux=history%>
                    <% end %>
                    <% if !(@aux.cellule_id!=history.cellule_id || @aux.creation_id!=history.creation_id)%>
                      <% next %>
                    <% end %>
                    <% if history.cellule_id%>
                      <tr>
                        <td><%=history.cellule.name%></td>
                        <td><%=l history.updated_at.to_date%></td>
                      <tr>
                    <%end%>
                    <% if history.creation_id%>
                      <tr>
                        <td><%=history.creation.name%></td>
                        <td><%=l history.updated_at.to_date%></td>
                      </tr>
                    <% end %>
                    <%@aux=history%>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>