config/routes.rb
Rails.application.routes.draw do


  resources :companies
  mount Ckeditor::Engine => '/ckeditor'
  get 'comments/create'

  get 'd/:short/metas/:id/nova', to: 'goals#new',as: :new_direction_goal
  get 'células/:id/metas/:id/nova', to: 'goals#new_goal',as: :new_cellule_goal
  get 'empresa/:id/metas/:id/nova', to: 'goals#new_goal_company',as: :new_company_goal

 
  get 'metas/:id/tarefas/:id/nova', to: 'tasks#new', as: :new_goal_task
  post 'tarefas/:id/confimation',to: 'goals#confimation',as: :confimation_goal_task
  post 'tarefas/:id/not_confirmation', to:'goals#not_confimation',as: :not_confimation_task
  
  resources :tasks, except: [:new,:index]
  resources :goals, except: [:new,:index]
  resources :skills

  root to: "welcome#home"
  
  resources :forums do
    member do
      put "like", to: "forums#vote"
      put "dislike", to: "forums#downvote"
    end
    resources :notes
  end

  resources :projects do
    resources :tecnologies
  end
  resources :cellules
  resources :directions,:path=>'d'



  resources :articles do
    member do
      put "like", to: "articles#vote"
      put "dislike", to: "articles#downvote"
    end
    resources :comments
  end

  get 'users/:id/change', to: 'users#change', as: :change_user
  post 'users/:id/give_up', to: 'users#give_up', as: :give_up_user
  post 'users/:id/accept', to: 'users#accept', as: :accept_user
  devise_for :users
  resources :users
  get 'welcome/home'
  get 'tags/:tag', to: 'forums#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :projects, :path =>'projetos'
  resources :cellules, :path=>'celulas'
  resources :directions

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    if user==Direction.find_by(short: 'gp').director
      can :manage, User.where.not(kind: 'admin')
    end

    if Direction.find_by(director: user)
      can :manage, Direction.find_by(director: user)
    end

    if Cellule.find_by(manager_id: user)
      can :manage, Cellule.find_by(manager_id: user)
    end
    if user.admin?
      can :manage, :all
      can :update, :all

    elsif user.manager?

      can :manage, user.cellules 
      can :update, user

    elsif user.director?
      can :manage, user.direction if user.direction.director==user
      can :update, user
      
    else
      can :update, user
      can :read, :all
    end
    if !user.admin?
      can :update, Forum, user_id: user.id
      can :destroy, Forum, user_id: user.id
      can :destroy, Note, user_id: user.id
      can :update, Article, user_id: user.id
      can :destroy, Article, user_id: user.id
      can :destroy, Comment, user_id: user.id
    end
    if user.gp_director?
      can :create, User
      can :update, User
    end
    if user.pro_director? or user.pmo_manager?
      can :create, Project
    end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments,  dependent: :destroy

  acts_as_votable
end

app/models/cellule.rb
class Cellule < ApplicationRecord
  validates :name,presence: true
  
  belongs_to :direction, optional: true
  belongs_to :manager, :class_name => 'User', optional: true,:foreign_key => 'manager_id'
  has_many :cellule_users
  has_many :users
  has_many :goals
  
  has_many :history_cellules
end

app/models/cellule_user.rb
class CelluleUser < ApplicationRecord
  belongs_to :user
  belongs_to :cellule
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/direction.rb
class Direction < ApplicationRecord
  validates :name,presence: true
  
  belongs_to :director, :class_name => 'User', optional: true,:foreign_key => 'director_id'
  has_many :cellules;
  has_many :users
  has_many :goals
  has_many :directionusers

  validates :short, uniqueness: true,presence: true

  def to_param
    short
  end
end

app/models/forum.rb
class Forum < ApplicationRecord
  belongs_to :user

  acts_as_taggable
  has_many :notes, dependent: :destroy

  acts_as_votable
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :direction,optional: true
  belongs_to :cellule,optional: true
  belongs_to :company,optional: true
  has_many :tasks,dependent: :destroy
end

app/models/history_user.rb
class HistoryUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :forum
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name,:description,:condition, presence: true
  
  has_many :history_users
  has_many :user_projects
  has_many :users, through: :user_projects
  belongs_to :director, :class_name => "User",:foreign_key => 'director_id'
  belongs_to :manager, :class_name => "User",:foreign_key => 'manager_id'
  
  has_many :tecnologies
  accepts_nested_attributes_for :tecnologies, allow_destroy: true
  #, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }

  enum condition:{
    active: 1,
    stopped: 2,
    finished: 3,
    late: 4
  }
end

app/models/skill.rb
class Skill < ApplicationRecord

  has_many :user_skills
  has_many :users,through: :user_skills
  enum kind:{
    programming: 1,
    management: 2

  }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :goal
end

app/models/tecnology.rb
class Tecnology < ApplicationRecord
  belongs_to :project, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates_format_of :email, with: /\A([^@\s]+)@injunior.com\z/i, on: [:create,:update]

  has_many :forums
  has_many :notes
  has_many :articles
  has_many :comments

  acts_as_voter
  
  belongs_to :direction,optional: true
  belongs_to :direction_fusion, :class_name => 'Direction', optional: true,:foreign_key => 'direction_fusion_id'
  
  belongs_to :cellule, optional: true
  belongs_to :creation,:class_name => "Cellule", :foreign_key => 'creation_id',optional: true
  has_many :history_cellules
  
  
  mount_uploader :avatar, AvatarUploader 

  has_many :user_projects
  has_many :projects, through: :user_projects

  has_many :user_skills
  has_many :skills,through: :user_skills
  accepts_nested_attributes_for :skills, allow_destroy: true

  has_many :direction_users


  enum kind:{
    standard: 1,
    manager: 2,
    director: 3, 
    admin: 4,
    gp_director: 5,
    pro_director: 6,
    pmo_manager: 7
  }

  def self.search(search)
    if search!='' and !search.nil?
      where(["name LIKE ?","%#{search}%"])
    else
      all
    end
  end

end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/helpers/goals_helper.rb
module GoalsHelper
  def can_manage_goal?(goal)
    if current_user.admin?
      return true
    end
    
    if goal.direction
      if (goal.direction.director==current_user) 
        return true
      end
    end
    if goal.cellule
      if goal.cellule.manager==current_user
        return true
      end
    end
    return false

  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/shared/_header.html.erb
<header>
    <nav class="navbar navbar-expand-sm navbar-dark">

        <%= link_to image_tag("logo_colorida.svg"), root_path, class: "navbar-brand logo" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse nav-menu" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <%= link_to root_path, class: "nav-link" do %>
                    <i class="fas fa-home"></i>
                    <span class="title-link">Início</span><span class="sr-only">(current)</span>
                    <% end %>
                </li>
                <li class="nav-item active">
                    <%= link_to forums_path, class: "nav-link" do %>
                    <i class="fas fa-comments"></i>
                    <span class="title-link">Fórum</span><span class="sr-only">(current)</span>
                    <% end %>
                </li>
                <li class="nav-item dropdown">
                    <span class="nav-link dropdown-toggle dropdown-nav" id="navbarDropdown" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user-tie"></i>
                        <span class="title-link">Diretorias</span>
                    </span>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to "Projetos", directions_path + "/p", class: "dropdown-item"%>
                        <div class="dropdown-divider"></div>
                        <%= link_to "Operacao", directions_path + "/op", class: "dropdown-item"%>
                        <div class="dropdown-divider"></div>
                        <%= link_to "Gestão de Pessoas", directions_path + "/gp", class: "dropdown-item"%>
                    </div>
                </li>
                <li class="nav-item active">
                        <%= link_to cellules_path, class: "nav-link" do %>
                        <i class="fas fa-boxes"></i>
                        <span class="title-link">Células</span><span class="sr-only">(current)</span>
                        <% end %>
                </li>
                <li class="nav-item active">
                        <%= link_to users_path, class: "nav-link" do %>
                        <i class="fas fa-users"></i>
                        <span class="title-link">Membros</span><span class="sr-only">(current)</span>
                        <% end %>
                </li>
                <li class="nav-item active">
                        <%= link_to projects_path, class: "nav-link" do %>
                        <i class="fas fa-history"></i>
                        <span class="title-link">Histórico</span><span class="sr-only">(current)</span>
                        <% end %>
                </li>
                <li class="nav-item active">
                        <%= link_to destroy_user_session_path , method: :delete, class: "nav-link" do %>
                        <i class="fas fa-door-open"></i>
                        Sair<span class="sr-only">(current)</span>
                        <% end %>
                </li>
            </ul>

        </div>
    </nav>
</header>

app/views/shared/_sidebar.html.erb
<nav id="sidebar">
    <div class="sidebar-header">
        <%= link_to user_path(current_user.id) do %>
        <%if current_user.avatar_url%>
        <%=image_tag current_user.avatar_url, class: "avatar"%>
        <%else%>
        <%=image_tag "wolf-avatar.jpg", class: "avatar"%>
        <% end %>
        <%end%>
    </div>
    <div class="btn-group-vertical grupo-botao" role="group" aria-label="Basic example">
        <%= link_to new_article_path, class: "nav-link" do %>
        <button type="button" class="btn btn-primary button-sidebar">
            <i class="fas fa-plus"></i>
            Artigo
        </button>
        <% end %>
        <%= link_to new_forum_path, class: "nav-link" do %>
        <button type="button" class="btn btn-primary button-sidebar">
            <i class="fas fa-plus"></i>
            Pergunta
        </button>
        <% end %>
        <% link_projetos = user_path(current_user.id) + "#projects"%>
        <%= link_to link_projetos, class: "nav-link" do %>
        <button type="button" class="btn btn-primary button-sidebar">
            Meus Projetos
        </button>
        <% end %>
    </div>

    <div class="pesquisa">
        <% if current_page?("forum") or current_page?("tag")%>
        <%=form_tag forums_path, :method => 'get' do%>
        <%= text_field_tag :search, params[:search], placeholder: "Pesquise uma tag"%>
        <%= button_tag(type: "submit", class: "btn btn-primary button-sidebar") do %>
        <i class="fas fa-search"></i>
        <% end %>
        <% end %>
        <%else%>
        <%=form_tag articles_path, :method => 'get' do%>
        <%= text_field_tag :search, params[:search], placeholder: "Pesquise uma artigo" %>
        <%= button_tag(type: "submit", class: "btn btn-primary button-sidebar") do %>
        <i class="fas fa-search"></i>
        <% end %>
        <% end %>
        <% end %>
    </div>
</nav>
<div>
</div>