config/routes.rb
Rails.application.routes.draw do


  resources :companies
  mount Ckeditor::Engine => '/ckeditor'
  get 'comments/create'

  get 'd/:short/metas/:id/nova', to: 'goals#new',as: :new_direction_goal
  get 'células/:id/metas/:id/nova', to: 'goals#new_goal',as: :new_cellule_goal
  get 'empresa/:id/metas/:id/nova', to: 'goals#new_goal_company',as: :new_company_goal

 
  get 'metas/:id/tarefas/:id/nova', to: 'tasks#new', as: :new_goal_task
  post 'tarefas/:id/confimation',to: 'goals#confimation',as: :confimation_goal_task
  post 'tarefas/:id/not_confirmation', to:'goals#not_confimation',as: :not_confimation_task
  
  resources :tasks, except: [:new,:index]
  resources :goals, except: [:new,:index]
  resources :skills

  root to: "welcome#home"
  
  resources :forums do
    member do
      put "like", to: "forums#vote"
      put "dislike", to: "forums#downvote"
    end
    resources :notes
  end

  resources :projects do
    resources :tecnologies
  end
  resources :cellules
  resources :directions,:path=>'d'



  resources :articles do
    member do
      put "like", to: "articles#vote"
      put "dislike", to: "articles#downvote"
    end
    resources :comments
  end

  get 'users/:id/change', to: 'users#change', as: :change_user
  post 'users/:id/give_up', to: 'users#give_up', as: :give_up_user
  post 'users/:id/accept', to: 'users#accept', as: :accept_user
  devise_for :users
  resources :users
  get 'welcome/home'
  get 'tags/:tag', to: 'forums#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :projects, :path =>'projetos'
  resources :cellules, :path=>'celulas'
  resources :directions

end

app/models/project.rb
class Project < ApplicationRecord
  validates :name,:description,:condition, presence: true
  
  has_many :history_users
  has_many :user_projects
  has_many :users, through: :user_projects
  belongs_to :director, :class_name => "User",:foreign_key => 'director_id'
  belongs_to :manager, :class_name => "User",:foreign_key => 'manager_id'
  
  has_many :tecnologies
  accepts_nested_attributes_for :tecnologies, allow_destroy: true
  #, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }

  enum condition:{
    active: 1,
    stopped: 2,
    finished: 3,
    late: 4
  }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.order('updated_at DESC')
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    #redirect_back(fallback_location: fallback_location)
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
    @aux=@project.user_ids
    if @project.manager_id
      @aux.append(@project.manager_id)
    end
    if @project.director_id
      @aux.append(@project.director_id)
    end
    @project.update_attributes(user_ids: @aux)
    @project.update_attributes(start: @project.created_at)
  end



  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    #tecs = Tecnology.where(project_id: @project.id)
    #logies = tecs
    #logies.each do
    #logies.attributes = tecs.attributes
    #tecs.each(&:destroy!)
    #@project.tecnologies.attributes = logies.attributes
    #  @project.t_attributes = {_destroy: '1'}
    #  @project.t.marked_for_destruction?
    #  @project.t.save
    #  @project.t.reload
    #end
    #@project.tecnologies = []
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
    @aux=@project.user_ids
    if @project.manager_id
      @aux.append(@project.manager_id)
    end
    if @project.director_id
      @aux.append(@project.director_id)
    end
    @project.update_attributes(user_ids: @aux)

    if @project.condition=='finished'
      @project.update_attributes(finish: @project.updated_at)
    end

    for user_id in @project.user_ids
      HistoryUser.create(user_id: user_id, project_id: @project.id)
    end

  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :condition, :description, :manager_id, :director_id, {:user_ids => []}, tecnologies_attributes: [:name, :_destroy, :id, :project_id])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def option_condition_project
    [["Ativo", :active],["Finalizado", :finished],["Parado", :stopped],["Atrasado", :late]]
  end

  def option_translate_project(option)
    if option=='active'
      'Ativo'
    elsif option=='finished'
      'Finalizado'
    elsif option=='stopped'
      'Parado'
    elsif option=='late'
      'Atrasado'
    end
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |f| %>
<% if project.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

  <ul>
    <% project.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :director_id%>
  <%= f.collection_select :director_id, User.all, :id, :name, :include_blank=>true%>
</div>

<div class="field">
  <%= f.label :manager_id%>
  <%= f.collection_select :manager_id, User.all, :id, :name, :include_blank=>true%>
</div>

<div class="field">
  <%= f.label :condition %>
  <%= f.select :condition, option_condition_project, :include_blank => true%>
</div>



<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<%= f.fields_for :tecnologies do |builder| %>
<%= render 'tecnology_fields', f: builder %>
<% end %>
<%= link_to_add_fields "Adicione uma tecnologia", f, :tecnologies %>

<div class="field">
  <%= hidden_field_tag "project[user_ids][]", nil%>
  <%= f.label "Integrantes" %>
  <% User.all.each do |user| %>
  <%= label_tag dom_id(user), user.name %>
  <%= check_box_tag "project[user_ids][]", user.id, @project.user_ids.include?(user.id), id: dom_id(user)%>
  <% end %>
</div>

<div class="actions">
  <%= button_tag(type: "submit", class: "btn btn-primary botao") do %>
  <i class="fas fa-plus"></i> Projeto
  <% end %>
</div>
<% end %>

app/views/projects/_tecnology_fields.html.erb
<fieldset>
  <%= f.label :name, "Tecnologia:" %>
  <%= f.text_field :name %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/projects/edit.html.erb
<section class="projetos-page">

  <%= render 'shared/sidebar' %>

  <div class="projetos-container">

    <div class="projetos-header">
      <h1> <i class="fas fa-code"></i> Editar projeto</h1>
      <%= link_to new_project_path, class: "nav-link" do %>
      <button type="button" class="btn btn-primary button-projetos">
        <i class="fas fa-plus"></i>
        Projeto
      </button>
      <% end %>
    </div>

    <div class="projects projects-form cointainer">
        <%= render 'form', project: @project %>
    </div>


  </div>



</section>

app/views/projects/index.html.erb
<section class="projetos-page">

  <%= render 'shared/sidebar' %>

  <div class="projetos-container">

    <div class="projetos-header">
      <h1> <i class="fas fa-code"></i> Projetos</h1>
      <%if can? :create, Project%>
      <%= link_to new_project_path, class: "nav-link" do %>
      <button type="button" class="btn btn-primary button-projetos">
        <i class="fas fa-plus"></i>
        Projeto
      </button>
      <% end %>
      <%end%>
    </div>

    <div class="projects cointainer">
      <% if @projects.where.not(condition: 'finished').length > 0%>
      <div class="ongoing">
        <h2>Em andamento</h2>
        <table>
          <tr>
            <th>Nome do Projeto</th>
            <!-- <th>Descrição</th> -->
            <th>Data de Inicio</th>
          </tr>
          <% for project in @projects.where.not(condition: 'finished')%>
          <tr>
            <td>
              <%= link_to project.name, project_path(project)%>
            </td>
            <td>
              <%=project.start.try(:strftime, ("%d/%m/%Y"))%>
            </td>
          </tr>
          <% end %>
        </table>
      </div>
      <% end %>
      <% if @projects.where(condition: 'finished').length > 0 %>
      <div class="finished">
        <h2>Concluídos</h2>
        <table>
          <thead>
            <tr>
              <th>Nome do Projeto</th>
              <!-- <th>Descrição</th> -->
              <th>Data de Inicio</th>
              <th>Data de Conclusão</th>
            </tr>
            <% for project in @projects.where(condition: 'finished')%>
            <tr>
              <td>
                <%= link_to project.name, project_path(project)%>
              </td>
              <td>
                <%=project.start.try(:strftime, ("%d/%m/%Y"))%>
              </td>
              <td>
                <%=project.finish.try(:strftime, ("%d/%m/%Y"))%>
              </td>
            </tr>
            <% end%>
        </table>
      </div>
      <% end %>
    </div>
  </div>

</section>

app/views/projects/new.html.erb
<section class="projetos-page">

  <%= render 'shared/sidebar' %>

  <div class="projetos-container">

    <div class="projetos-header">
      <h1> <i class="fas fa-code"></i> Novo projeto</h1>
      <%= link_to new_project_path, class: "nav-link" do %>
      <button type="button" class="btn btn-primary button-projetos">
        <i class="fas fa-plus"></i>
        Projeto
      </button>
      <% end %>
    </div>

    <div class="projects projects-form cointainer">
        <%= render 'form', project: @project %>
    </div>


  </div>



</section>

app/views/projects/show.html.erb
<section class="projetos-page">

  <%= render 'shared/sidebar' %>

  <div class="projetos-container">

    <div class="projetos-header">
      <h1> <i class="fas fa-code"></i> Projeto
        <%=@project.name%>
      </h1>
      <%= link_to new_project_path, class: "nav-link" do %>
      <button type="button" class="btn btn-primary button-projetos">
        <i class="fas fa-plus"></i>
        Projeto
      </button>
      <% end %>
    </div>

    <div class="projects cointainer">

      <p>
        <span class="title">Descrição:</span>
        <%= @project.description %>
      </p>

      <p>
        <span class="title">Status:</span>
        <%= option_translate_project(@project.condition) %>
      </p>

      <p>
        <span class="title">Tecnologias:</span>
        <% @project.tecnologies.each do |tec| %>
        <ul>
          <li>
            <%=tec.name%>
          </li>
        </ul>
        <%end%>
      </p>

      <div class="usuarios-projeto">
        <span class="title">Membros:</span>
        <div class="usuario-avatar">
          <% @project.users.where.not(id: @project.director_id).where.not(id: @project.manager_id).each do |user| %>
          <div>
            <%= link_to user_path(user.id) do %>
            <div class="usuario">
              <% if user.avatar_url %>
              <%= image_tag user.avatar_url %>
              <% else %>
              <%= image_tag "wolf-avatar.jpg"%>
              <% end %>
              <%= user.name %>
            </div>
            <%end%>
          </div>
          <%end%>
        </div>
      </div>

      <div class="botoes">
        <% if can? :update, @project%>
        <%= link_to edit_project_path(@project) do %>
        <button type="button" class="btn btn-primary botao">
          <i class="far fa-edit"></i>
        </button>
        <% end %>
        <% end %>

        <%= link_to projects_path do %>
        <button type="button" class="btn btn-primary botao">
          <i class="fas fa-arrow-left"></i>
        </button>
        <% end %>

      </div>
    </div>


  </div>
</section>
<% @no_repeat=[]%>
<% for history in @project.history_users%>
  
  <%if !(@project.users.include? history.user) && !(@no_repeat.include? history.user)%>
    <%=history.user.name%>
    <%@no_repeat.append(history)%>
  <% end %>
<%end%>